### ISSUE TITLE
Customization does not work as documented

### ISSUE THREAD

**Issue by hickst** [Caltech-IPAC/firefly#1143]
Using version `release-2021.3.2`, but also tested with `latest`.

I am attempting to load local customizations to the Firefly docker container, as documented here :

https://hub.docker.com/r/ipac/firefly

(but note that I did not use the incorrectly documented `docker run` line which should mount `/myDir` to `/local/www` and not to `local/www`).

Also, this very similar example from the source code does not work for me either:

https://github.com/Caltech-IPAC/firefly/blob/rc-2021.3/docker/base/customize-firefly.txt

**Steps to reproduce:**
```
> mkdir fftest
> dk run --rm -v $PWD/fftest:/local/www --name firefly ipac/firefly:latest --help
```
**NOTE: the generation pass works** and successfully creates the desired sample files (index.html, slate.html, and firefly-dev.html) in fftest. Now, edit the generated files to customize them and start 'local' Firefly:
```
> dk run -p8080:8080 -v $PWD/fftest:/local/www -m 4g --name firefly ipac/firefly:latest
```
Unfortunately, trying to open a browser window to `http://localhost:8080/local/`, fails with `404` error.
I also tried this similar URL, which also fails with `404`: `http://localhost:8080/local/www/`

However, the standard (uncustomized) Firefly display **is available**: `http://localhost:8080/firefly` and appears to work as normal.

**Comment by robyww** [comment]
> Unfortunately, trying to open a browser window to http://localhost:8080/local/

Just off the cuff….
If you new html file is `myFile.html` I think the url you want is http://localhost:8080/local/myFile.html
You might be able to you use http://localhost:8080/local/ if the the html file is `index.html`. If that does not work I will look closer tomorrow

**Comment by hickst** [comment]
Hi Trey,

The aforementioned directions in DockerHub specify the URLs that I showed and tried. But, explicitly using `index.html` does not work either. I think it is necessary to specify a directory because....

The 3 'local' files generated by the generation step are `index.html`, `slate.html`, and `firefly-dev.html`. I'm pretty sure the first two (at least) are 'hardcoded' filenames, meant to replace the existing default files of the same name; creating the initially displayed image screen and the initial tabs in the default Firefly application. (That is, all 3 files are 'expected' by the Firefly application).

**Comment by hickst** [comment]
I've been playing with this a little more.....

If I build a new Docker container, with the IPAC container as base, and copy the generated files into `/local/www` (at build time), then the documented 'local' URL (http://localhost:8080/local/) does work. But, of course, it would be **much** more convenient if I didn't have to build my own container to customize.

*Dockerfile:*
```
FROM ipac/firefly:release-2021.3.2
USER root
COPY fftest /local/www
```

**NOTE:** that the `USER root` line appears to be crucial to correct operation of the customized version. Without it, the 'local' URL fails and I observe several error messages in the Firefly runtime logs:

*catalina.2021-11-01.log:*
```
01-Nov-2021 19:48:17.269 SEVERE [main] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/usr/local/tomcat/conf/Catalina/localhost]
```

*firefly.log:*
```
11/01 19:48:23 ERROR   Thread: main  server.ServerContext#setSharedWorkingDir:366
        Cannot write to Shared Worked Dir: /firefly/shared-workarea/firefly
```

Without the switch to the `root` user the entire Firefly webapp is owned by (phantom) user and group '91'. This may have been an attempt to run the webapp as a non-root user but user and group 91 do not seem to have been created in the container first.

Git `blame` seems to show that user/group '91' replaced user/group 'tomcat' in the Dockerfile 
 (https://github.com/Caltech-IPAC/firefly/blame/dev/docker/base/Dockerfile) as part of issue #1038.

I hope any of this helps. If there is anything else you would like me to try, please let me know.
    regards,
        -tom

**Comment by hickst** [comment]
Has anyone gotten a chance to look at this issue yet?

**Comment by robyww** [comment]
@hickst - Sorry it took so long to reply. This got lost on my list and I just got back from vacation.

A couple of things:
- the user 91 is suppose to be user `tomcat`, we are specifically creating the user in the next release.
- The test works for me on my MAC. I am guessing you are using linux or a PC. It appears that OSX might be more lax about  security in reading files in the mapped directory. Trying seeing the security in `fftest` to world read. This might fix it. If  this works I will start thinking about what is the best course of action on our side.

**Comment by hickst** [comment]
@robyww Hi Trey

I'm working on macOS 10.15.7. At least the Mac generates the custom files: I also tried on an up-to-date Ubuntu 20.04 and it won't even generate the files:
```
docker pull ipac/firefly:latest
mkdir fftest
cd fftest
mkdir www
dk run --rm --name ffgen -v ${PWD}/www:/local/www ipac/firefly --help
```
Mixed in the voluminous help output are these error messages:
```
cp: cannot create regular file '/local/www/index.html': Permission denied
cp: cannot create regular file '/local/www/slate.html': Permission denied
cp: cannot create regular file '/local/www/firefly-dev.html': Permission denied
```
I'm pretty sure this is because the Firefly docker container is being executed as unknown user '91', which user does not exist on my Ubuntu system and does not have permission to create files on my disk.

**Comment by hickst** [comment]
Back to the Mac...I also believe that the unknown user '91' in the container is causing the issue with the generated custom pages. Here's what I did:
```
dk pull ipac/firefly:release-2021.4.0
mkdir fftest
cd fftest
mkdir www
dk run --rm --name ffgen -v ${PWD}/www:/local/www ipac/firefly --help
```
The files are correctly generated in `fftest/www`. (Note that this is a well-known difference in the way that Mac docker works vs Linux docker: files can be created by the container on (non read-only) bind-mounted directories and they have the "correct" owner).

Now I try to run with the custom files, per the Docker documentation:
```
dk run --rm --name fflocal -p 8888:8080 -v ${PWD}/www:/local/www -m 4g ipac/firefly:latest
```
The Firefly server starts up but we immediately see this message in the displayed catalina log file:
```
31-Jan-2022 01:03:30.204 SEVERE [main] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/usr/local/tomcat/conf/Catalina/localhost]
```

If we `exec` into the running Firefly container and look around we see a couple of issues. First, the container is running as unknown user '91' and this annoys Bash ("I have no name!"):
```
I have no name!@7aa0b5a0dd98:/usr/local/tomcat/logs$ whoami
whoami: cannot find name for user ID 91
```

 I try to list the directory which was noted in the SEVERE error:
```
I have no name!@7aa0b5a0dd98:/usr/local/tomcat/logs$ ls -l /usr/local/tomcat/conf/Catalina/localhost
ls: cannot access '/usr/local/tomcat/conf/Catalina/localhost': Permission denied
```

Looking at the permissions of things "higher up":
```
I have no name!@7aa0b5a0dd98:/usr/local/tomcat/logs$ ls -l /usr/local/tomcat/conf/
drwxr--r-- 1 root root   4096 Dec 14 21:28 Catalina/
-rw-r--r-- 1 root root  12953 Dec  2 14:30 catalina.policy
-rw-r--r-- 1 root root   7276 Dec  2 14:30 catalina.properties
-rw-r--r-- 1 root root   1424 Dec 14 21:28 context.xml
-rw-r--r-- 1 root root   1149 Dec  2 14:30 jaspic-providers.xml
-rw-r--r-- 1 root root   2313 Dec  2 14:30 jaspic-providers.xsd
-rw-r--r-- 1 root root   4144 Dec  2 14:30 logging.properties
-rw-r--r-- 1 root root   7606 Dec 14 21:28 server.xml
-rw-r--r-- 1   91   91    211 Jan 31 01:03 tomcat-users.xml
-rw-r--r-- 1 root root    209 Dec 14 21:28 tomcat-users.xml.in
-rw-r--r-- 1 root root   2558 Dec  2 14:30 tomcat-users.xsd
-rw-r--r-- 1 root root 172359 Dec  2 14:30 web.xml
```
Note that the permissions on Catalina prevent anyone but root from even listing the directory contents:
```
$ ls -l /usr/local/tomcat/conf/Catalina/
ls: cannot access '/usr/local/tomcat/conf/Catalina/localhost': Permission denied
total 0
d????????? ? ? ? ?            ? localhost/
```
Back at the Chrome browser, entering the URL specified in the DockerHub instructions:
```
http://localhost/local/
```
produces an HTTP 404 response. The same 404 response is also produced on Safari.

Note that the non-custom URL still brings up the non-customized Firefly:
```
http://localhost/firefly/
```

**Comment by robyww** [comment]
We think the solution may be to use the `-u` option in the `docker run` command.  That will cause the docker container to run as that user. My default it runs with a tomcat user id of 91.

So, `docker run -u myUserName...` (the user name is the owner of the external directory) might fix the writing and reading issues. I think this will fix the main problem We have discovered a couple of other `permission denied` type issue we are fixing in the next release, but I don't think they are related to the problem you are seeing.

**Comment by hickst** [comment]
@robyww I downloaded and tested yesterday's release (2022.1). Now that the Tomcat user issue has been addressed, the custom scripts are loading and running for me. Thanks for the new release. I am closing this issue.
