### ISSUE TITLE
wcs issue with Chandra Image

### ISSUE THREAD

**Issue by olaurino** [Caltech-IPAC/firefly#1430]
When I upload a Chandra image in Firefly there seems to be something wrong with the WCS. The FOV appears to be 0", and moving the cursor over the image shows always the initial coordinates. If I toggle the grid, only one line is displayed at the top and right edges of the view, confirming that the WCS information is off. DS9 correctly shows the coordinates, which probably rules out _obvious_ issues with the file itself.

I couldn't attach a FITS file, so please let me know how I can send you an image to reproduce the issue. Unfortunately I don't have an easy way to provide a direct URL to an image either, which is usually part of an archived tarball or the result of a query with a dedicated client.

To reproduce, I set the image search parameters as in the screenshot below:

![image](https://github.com/Caltech-IPAC/firefly/assets/5692321/0cc20918-9b82-47ed-9891-cc7885efd731)

And the image view appears as in the screenshot below:

![image](https://github.com/Caltech-IPAC/firefly/assets/5692321/5fd4571c-894d-495b-8773-5f6153e8e7f2)

I could reproduce the issue with the RSP portal and my own prototype of the Nexus deployment.

**Comment by robyww** [comment]
Can you put the image in Box or Dropbox and share the link?

**Comment by olaurino** [comment]
right, I use those so very little that I didn't even think about it:

https://drive.google.com/file/d/1W-Qhbg9OYRM-1uUlj1-_db1cXCIXxO2I/view?usp=drive_link

**Comment by robyww** [comment]
We will fix this in our upcome patch release today or tomorrow. https://github.com/Caltech-IPAC/firefly/pull/1431

**Comment by robyww** [comment]
`PC1_1` and `PC2_2` are not defined in the header. In that case they should default to CDELT1 and CDELT2. We where not doing the default correctly. 

If reality we convert PC stuff to CD stuff so in the code change you will actually see in the PR is to default `CD1_1` and `CD2_2` defaulted to `CDELT1` and `CDELT2`.

I found the reference for the default here: https://lweb.cfa.harvard.edu/~jzhao/SMA-FITS-CASA/docs/wcs88.pdf
