### ISSUE TITLE
Consider creating a Debian package

### ISSUE THREAD

**Issue by olebole** [Caltech-IPAC/firefly#480]
Follow-up on #472:

@cwang2016 Since you already were digging into Debian; could you imagine packaging firefly for Debian? Apart from advantages for users, this gives you a lot of code review and QA :-)

**Comment by ejoliet** [comment]
@olebole We can think about it but it won't happen in the short term. We will look into it as soon as we get the chance. Thanks for the suggestion.

**Comment by robyww** [comment]
Closing this issue.  Docker is now our direction. This seems to solve many packaging and distribution problems.
