### ISSUE TITLE
Please update README documentation on numerous branches

### ISSUE THREAD

**Issue by hickst** [Caltech-IPAC/firefly#712]
I'm trying to build from a relatively recent, stable version but can't figure out which branch that would be, among the myriad of branches. The README (https://github.com/Caltech-IPAC/firefly/tree/dev#branches) is out-of-date on this issue, as it says:

"master: Update once a week. Used for our relatively stable, weekly build" but `master` hasn't been updated **since Nov 15, 2017**.

"rc: the next release canidate branch. This is the most stable branch" but `rc` is 5 commits ahead, 43 commits behind `dev`.

`release-2018.2` looks like it might be a good candidate: it's only 5 days old (at the point of this writing) but it's not even mentioned in the README, is 4 commits ahead of `rc`, and 9 commits ahead, 43 commits behind `dev`.

Please let us know which branch will produce a stable, useable, recent Firefly server and then update the documentation accordingly. Thanks.

**Comment by robyww** [comment]
You are right, the README is confusing and out of date. We do plan to make a push in updating our documentation after the first of the year. 

Our new branching plan is in this file. 
https://github.com/Caltech-IPAC/firefly/blob/test-branch-docs/docs/tags-and-branches.md

Right now (12-19-2018) the branch: `release-2018.2` is what you should use. In the future the branch will be `rc-year-#` and the release out of that branch will be tagged `release-year-#.rev` as described in the document above. We are doing away with the `master` plan that you saw.

We are really encouraging the use of docker for Firefly releases. Currently you could do a docker run with firefly using the tab `ipac/firelfy:release-2018.2`. A quick overview of the firefly docker documentation can be found using the command:
`docker run --rm ipac/firefly:release-2018.2 -help`

Will are also planning move to more formal quarterly releases next year, but we still have some details for work out.

I think you have my email, you are also welcomed to email me as well.

**Comment by hickst** [comment]
Thanks for the quick and informative reply!
I will also definitely consider using the docker image.
Have a good holidays.
