### ISSUE TITLE
Leaving cutout size blank causes bad URL to be sent to server

### ISSUE THREAD

**Issue by hickst** [Caltech-IPAC/firefly#910]
Using ipac/firefly:rc-2019.3 (docker image id d527645e85a0)

In the `Images` dropdown, `3. Select Target` area, the `Cutout size` box says "**(leave blank for full size)**". **If** the box is left blank, however, the `size` arguments (i.e., `size, sizeDeg, sizeArcMin, sizeArcSec`) are not filled in the outgoing URL and so the URL contains strings like `${sizeDeg}`, etc., which causes malformed URL errors when received by the image/cutout server.

Here is a sample error log from a Flask image/cutout server showing the problematic, incoming URL with unexpanded arguments:
```
[2019-11-06 23:44:07 +0000] [8] [ERROR] Error handling request /img/co/cut?ra=53.16&dec=-27.78&size=${size}&sizeDeg=${sizeDeg}&sizeArcMin=${sizeArcMin}&sizeArcSec=${sizeArcSec}&filter=F090W

......most of Traceback omitted.......

  File "/cuts/cuts/blueprints/img/tasks.py", line 199, in parse_cutout_args
    co_args['size'] = float(sizeArcMinStr)
ValueError: could not convert string to float: '${sizeArcMin}'
10.0.13.4 - [06/Nov/2019:23:44:07 +0000] "GET /img/co/cut?ra=53.16&dec=-27.78&size=${size}&sizeDeg=${sizeDeg}&sizeArcMin=${sizeArcMin}&sizeArcSec=${sizeArcSec}&filter=F090W HTTP/1.1" 500 0 in 23301µs (0.023301s)
```

**Comment by robyww** [comment]
Yes, I can see how that would happen.  What would be the correct substitution? An empty string?

I will make a ticket.

**Comment by hickst** [comment]
Thanks Trey. I think the empty string would work well; the keywords would remain but they would have no value:
```
http://localhost:8000/img/co/cut?ra=53.16&dec=-27.78&size=&sizeDeg=&sizeArcMin=&sizeArcSec=&filter=F090W
```
In my experience most URL argument parsers put the args into a hashmap/dictionary and so the arguments would appear to be absent when looked up (as desired).

**Comment by robyww** [comment]
fixed as part of the work in in PR #912, This will either go into a 2019.3  patch or 2019.4 we have not yet decided.

**Comment by hickst** [comment]
Thanks! From my viewpoint, the sooner the better (as the prompt on the `Cutout size` box tells users that it is a legal thing to do and I will soon have some inexperienced users).

**Comment by robyww** [comment]
ok, we are putting it in 2019.3.2

**Comment by hickst** [comment]
Thanks...good timing...I just finished updating my little image server to handle the case where the sizes where absent and the entire image should be returned (so I'm ready :).

**Comment by hickst** [comment]
@robyww Just a footnote to say this is working well...thanks for the timely fix.
